"""test_docs_dotfile_gitignore_coverage.py -- WI-0058: generated docs/.<name>
artifacts must be gitignored, both in this repo and in every project
scripts/project-init.sh scaffolds.

## Background

CCPR's shipped scripts and slash commands write a fixed set of volatile
dotfiles under docs/ -- session snapshots, gate preflight notes, quality-scan
reports. None of that is content this repository, or any project generated by
it, should ever commit. A verification run on 20.08.2026 left
docs/.session-context.md untracked in this repo's working tree because
CCPR's own .gitignore covered none of them, which is exactly the shape
instinct G-049 exists to prevent: a volatile skill output needs its
.gitignore entry at the moment the skill is designed, not discovered by
accident afterwards.

A sweep at that point (`git check-ignore` against every docs/.<name> path
named literally in scripts/ and commands/) found three distinct, independent
gaps:

1. This repository's own .gitignore covered none of the twelve.
2. scripts/project-init.sh's generated .gitignore (what new projects get)
   covered three of the five *kinds* of artifact but not
   docs/.cross-check-report.md, even though that path is named explicitly in
   the "Standard block for .gitignore in CCPR projects" CCPR itself ships as
   instinct G-049.
3. docs/.baseline-prep.md was in neither the generator nor the shipped
   standard block -- newer than both, and exactly the drift G-049 exists to
   prevent.

## What this test derives, and what it cannot see

`swept_docs_dotfile_paths()` re-derives the expected set the same way the
original sweep did: grep scripts/ and commands/ for literal `docs/\\.<name>`
path fragments ending in `.md` or `.json`. It does NOT hand-maintain a list --
a new generated artifact added to a shipped script or command tomorrow
enters this set automatically and this test fails until someone lists it in
every place that must agree.

The method's limitation is real and deliberate, not hidden: it only finds
paths spelled out LITERALLY in the source. scripts/gate-preflight.py builds
its actual output path from an f-string
(`f".gate-preflight-{phase}.md"`, scripts/gate-preflight.py:421) -- the
generator that writes the file contributes nothing to this sweep. The eight
concrete docs/.gate-preflight-p0.md .. p7.md hits this sweep finds come
entirely from each commands/gate-pN.md file documenting the preflight note
gate-preflight.py will have written for that phase, not from the generator
itself. A path assembled purely at runtime, never spelled out anywhere in
scripts/ or commands/, would not be found by this test.
"""

import re
import subprocess
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
COMMANDS_DIR = REPO_ROOT / "commands"
GITIGNORE = REPO_ROOT / ".gitignore"
PROJECT_INIT = REPO_ROOT / "scripts" / "project-init.sh"

# Every file carrying a copy of the "Standard block for .gitignore in CCPR
# projects" (instinct G-049). Both must agree with each other and with what
# project-init.sh actually generates -- a rule that contradicts its own
# generator is worse than no rule.
STANDARD_BLOCK_CARRIERS = (
    REPO_ROOT / "templates" / "STARTER_INSTINCTS.md",
    REPO_ROOT / "instincts" / "workflow.md",
)

DOTFILE_RE = re.compile(r"docs/\.[A-Za-z0-9_*-]+\.(?:md|json)")
GATE_PREFLIGHT_CONCRETE_RE = re.compile(r"^docs/\.gate-preflight-p\d+\.md$")


def shipped_source_files():
    """Files this sweep treats as "shipped scripts and commands" -- the same
    scope test_shell_script_syntax.py already documents for scripts/: top-level
    scripts/*.sh and scripts/*.py plus scripts/lib/*.sh and scripts/lib/*.py.
    scripts/tests/** is the test suite itself, not a shipped artefact (and
    sweeping it would make this test find its own docstring); scripts/local-llm/**
    is user-owned/hardware-specific per install.sh's PROTECTED marking. commands/
    is flat and fully in scope.
    """
    files = []
    for pattern in ("*.sh", "*.py"):
        files.extend(SCRIPTS_DIR.glob(pattern))
        files.extend((SCRIPTS_DIR / "lib").glob(pattern))
    files.extend(COMMANDS_DIR.rglob("*.md"))
    return files


def swept_docs_dotfile_paths():
    """Every docs/.<name> path named literally in shipped scripts or commands.

    Raw hits, not normalised -- includes both the eight concrete
    docs/.gate-preflight-pN.md references and the docs/.gate-preflight-*.md
    glob project-init.sh's own generated block already writes.
    """
    hits = set()
    for path in shipped_source_files():
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        hits.update(DOTFILE_RE.findall(text))
    return hits


def concrete_artifact_paths():
    """Concrete (non-glob) paths -- what git check-ignore can be asked about."""
    return {p for p in swept_docs_dotfile_paths() if "*" not in p}


def block_patterns():
    """Normalised patterns an enumeration-style .gitignore block must list:
    the eight concrete gate-preflight hits collapse into the one glob form
    every generator/instinct block already uses for that family.
    """
    patterns = set()
    for hit in swept_docs_dotfile_paths():
        if GATE_PREFLIGHT_CONCRETE_RE.match(hit):
            patterns.add("docs/.gate-preflight-*.md")
        else:
            patterns.add(hit)
    return patterns


def git_check_ignore(rel_path):
    return subprocess.run(
        ["git", "check-ignore", "-q", rel_path],
        cwd=REPO_ROOT,
    ).returncode == 0


class DocsDotfileSweepTest(unittest.TestCase):
    """Characterises the sweep method itself, independent of any fix below --
    a regression here means the sweep's own scope silently changed."""

    def test_sweep_finds_the_thirteen_concrete_artifacts_after_wi_0021s_anchor_report(self):
        """Was twelve at WI-0058; WI-0021 (Teilwelle 4c) added docs/.anchor-report.md,
        named literally in commands/anchor.md's ## Result section."""
        self.assertEqual(  # pin: set docs-dotfile-concrete-artifacts
            concrete_artifact_paths(),
            {
                "docs/.anchor-report.md",
                "docs/.baseline-prep.md",
                "docs/.cross-check-report.md",
                "docs/.quality-scan-report.json",
                "docs/.session-context.md",
                "docs/.gate-preflight-p0.md",
                "docs/.gate-preflight-p1.md",
                "docs/.gate-preflight-p2.md",
                "docs/.gate-preflight-p3.md",
                "docs/.gate-preflight-p4.md",
                "docs/.gate-preflight-p5.md",
                "docs/.gate-preflight-p6.md",
                "docs/.gate-preflight-p7.md",
            },
        )

    def test_sweep_normalises_to_the_six_block_patterns_the_generator_uses(self):
        """Was five at WI-0058; see the thirteen-artifact test above for the addition."""
        self.assertEqual(  # pin: set docs-dotfile-block-patterns
            block_patterns(),
            {
                "docs/.anchor-report.md",
                "docs/.baseline-prep.md",
                "docs/.cross-check-report.md",
                "docs/.quality-scan-report.json",
                "docs/.session-context.md",
                "docs/.gate-preflight-*.md",
            },
        )


class ThisRepoGitignoreCoversEverySweptArtifactTest(unittest.TestCase):
    """Gap 1 from the WI-0058 sweep: this repository's own .gitignore."""

    def test_every_swept_artifact_is_ignored_in_this_repo(self):
        uncovered = sorted(
            p for p in concrete_artifact_paths() if not git_check_ignore(p)
        )
        self.assertEqual(
            uncovered, [],
            "docs/ artifacts named in scripts/ or commands/ but not covered "
            "by this repo's .gitignore: " + ", ".join(uncovered),
        )


class GeneratedProjectGitignoreBlockTest(unittest.TestCase):
    """Gap 2: scripts/project-init.sh's generated .gitignore, which is what a
    new CCPR project actually receives."""

    def test_project_init_gitignore_block_lists_every_swept_pattern(self):
        text = PROJECT_INIT.read_text(encoding="utf-8")
        missing = sorted(p for p in block_patterns() if p not in text)
        self.assertEqual(
            missing, [],
            "docs/ artifact patterns missing from scripts/project-init.sh's "
            "generated .gitignore block: " + ", ".join(missing),
        )


class StandardBlockAgreementTest(unittest.TestCase):
    """Gap 3: every file carrying a copy of the G-049 'Standard block for
    .gitignore in CCPR projects' must literally agree with the swept set --
    and therefore with each other and with project-init.sh's own generator.
    """

    def test_every_standard_block_carrier_lists_every_swept_pattern(self):
        for carrier in STANDARD_BLOCK_CARRIERS:
            with self.subTest(carrier=carrier.relative_to(REPO_ROOT)):
                text = carrier.read_text(encoding="utf-8")
                missing = sorted(p for p in block_patterns() if p not in text)
                self.assertEqual(
                    missing, [],
                    f"docs/ artifact patterns missing from {carrier}: "
                    + ", ".join(missing),
                )


if __name__ == "__main__":
    unittest.main()
